name: Tests and linters

on: [ push, pull_request, workflow_dispatch ]

jobs:

  tests-on-legacy-versions:
    name: Run tests on legacy versions
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, pypy3.9 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.python-version }}

  test-on-different-versions:
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, '3.10', 3.11, pypy3.10 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.python-version }}

  test-coverage:
    name: Run tests with coverage
    runs-on: ubuntu-22.04
    env:
      DEPENDENCY_INJECTOR_DEBUG_MODE: 1
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install tox cython
      - run: make cythonize
      - run: tox
        env:
          TOXENV: coveralls

  linters:
    name: Run linters
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        toxenv: [ flake8, pydocstyle, mypy, pylint ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
